spring.application.name=substituirpecas

spring.datasource.url=jdbc:mariadb://172.16.0.74/SubstituicaoPecas
spring.datasource.username=txc
spring.datasource.password=Ti@2015!*


spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.show-sql=false

spring.jpa.hibernate.ddl-auto=update

#TOTVS PROD:
totvs.api.baseUrl=https://apitotvsmoda.bhan.com.br
totvs.auth.clientId=txcapiv2
totvs.auth.clientSecret=6461456651
totvs.auth.username=USE.API
totvs.auth.password=txc2015
totvs.auth.grant-type=password
